from wtforms import Form, BooleanField, StringField, validators, SelectField

class Contact_Information(Form):
    firstName           = StringField('First Name*', [validators.Length(min=1, max=120)])
    middleName          = StringField('Middle Name', [validators.Length(min=0, max=120)])
    lastName            = StringField('Last Name*', [validators.Length(min=1, max=120)])
    referral            = SelectField('How did you hear about SER Jobs for Progress?*', choices =[('1', 'Please select...'), ('2', 'church flyer'), ('3', 'Church Presentation'), ('4', 'Community Agency Flyer'), ('5', 'Community Agency Staff'), ('6', 'Guidance Counselor'), ('7' 'HCC', "Information Session"), ('8', 'Internet/ Social Media'), ('9', 'Job Fair/ Hiring Event'), ('10', 'Ser Client/Alumni'), ('11', 'SER Staff'), ('12', 'United Way Helpline'), ('13', 'Workforce Solution'), ('14', 'Other')])
    streetAddress       = StringField('Street Address*', [validators.Length(min=1, max=120)])
    city                = StringField('City*', [validators.Length(min=1, max=120)])
    state               = SelectField('State*', choices=[('1', 'Texas'), ('2', 'Oklahoma'), ('3', 'Colorado'), ('4', 'California'), ('5', 'Ohio')])
    postalCode          = StringField('Postal Code*', [validators.Length(min=1, max=120)])
    county              = SelectField('County*', choices=[('1','Please select...'), ('2', 'Brazoria'), ('3', 'Chambers'), ('4', 'Fort Bend'), ('5', 'Galveston'), ('6', 'Harris'), ('7', 'Liberty'), ('8', 'Montgomery'), ('9', 'Waller'), ('10', 'Other')])
    socialSecurity      = StringField('Social Security #*', [validators.Length(min=0, max=9)])
    dateOfBirth         = StringField('Date of Birth*', [validators.Length(min=1, max=10)])
    email               = StringField('Email Address', [validators.Length(min=0, max=120)])
    workPhone           = StringField('Work Phone', [validators.Length(min=0, max=120)])
    mobilePhone         = StringField('Mobile Phone*', [validators.Length(min=1, max=120)])
    homePhone           = StringField('Home Phone', [validators.Length(min=0, max=120)])
    preferredPhone      = SelectField('Preferred Phone', choices=[('1', 'Please select...'), ('2', 'Home'), ('3', 'Work'), ('4', 'Mobile')])
    facebookPage        = StringField('Facebook Page', [validators.Length(min=0, max=125)])
    twitterHandle       = StringField('Twitter Handle', [validators.Length(min=0, max=125)])
    instagramUsername   = StringField('Instagram Username', [validators.Length(min=0, max=125)])
    linkedIn            = StringField('LinkedIn Profile', [validators.Length(min=0, max=125)])

    print("Im in the contact information")
